### ISSUE TITLE
error during pip installation

### ISSUE THREAD

**Issue by ad8e** [imbue-ai/carbs#1]
```
kevin@kevin-a40-0:~/clusterstorage$ git clone https://github.com/imbue-ai/carbs.git
Cloning into 'carbs'...
remote: Enumerating objects: 38, done.
remote: Counting objects: 100% (38/38), done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 38 (delta 6), reused 38 (delta 6), pack-reused 0
Receiving objects: 100% (38/38), 759.10 KiB | 19.98 MiB/s, done.
Resolving deltas: 100% (6/6), done.
kevin@kevin-a40-0:~/clusterstorage$ pip install -e carbs
Defaulting to user installation because normal site-packages is not writeable
Obtaining file:///mnt/clusterstorage/workspace/kevin/carbs
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [91 lines of output]
      /tmp/pip-build-env-ih3s6f7d/overlay/local/lib/python3.10/dist-packages/setuptools/config/_apply_pyprojecttoml.py:72: _MissingDynamic: `description` defined outside of `pyproject.toml` is ignored.
      !!
      
              ********************************************************************************
              The following seems to be defined outside of `pyproject.toml`:
      
              `description = 'CARBS hyperparameter tuning algorithm'`
      
              According to the spec (see the link below), however, setuptools CANNOT
              consider this value unless `description` is listed as `dynamic`.
      
              https://packaging.python.org/en/latest/specifications/pyproject-toml/#declaring-project-metadata-the-project-table
      
              To prevent this problem, you can list `description` under `dynamic` or alternatively
              remove the `[project]` table from your file and rely entirely on other means of
              configuration.
              ********************************************************************************
      
      !!
        _handle_missing_dynamic(dist, project_table)
      /tmp/pip-build-env-ih3s6f7d/overlay/local/lib/python3.10/dist-packages/setuptools/config/_apply_pyprojecttoml.py:72: _MissingDynamic: `license` defined outside of `pyproject.toml` is ignored.
      !!
      
              ********************************************************************************
              The following seems to be defined outside of `pyproject.toml`:
      
              `license = 'LICENSE.txt'`
      
              According to the spec (see the link below), however, setuptools CANNOT
              consider this value unless `license` is listed as `dynamic`.
      
              https://packaging.python.org/en/latest/specifications/pyproject-toml/#declaring-project-metadata-the-project-table
      
              To prevent this problem, you can list `license` under `dynamic` or alternatively
              remove the `[project]` table from your file and rely entirely on other means of
              configuration.
              ********************************************************************************
      
      !!
        _handle_missing_dynamic(dist, project_table)
      /tmp/pip-build-env-ih3s6f7d/overlay/local/lib/python3.10/dist-packages/setuptools/config/_apply_pyprojecttoml.py:72: _MissingDynamic: `authors` defined outside of `pyproject.toml` is ignored.
      !!
      
              ********************************************************************************
              The following seems to be defined outside of `pyproject.toml`:
      
              `authors = 'Untitled AI'`
      
              According to the spec (see the link below), however, setuptools CANNOT
              consider this value unless `authors` is listed as `dynamic`.
      
              https://packaging.python.org/en/latest/specifications/pyproject-toml/#declaring-project-metadata-the-project-table
      
              To prevent this problem, you can list `authors` under `dynamic` or alternatively
              remove the `[project]` table from your file and rely entirely on other means of
              configuration.
              ********************************************************************************
      
      !!
        _handle_missing_dynamic(dist, project_table)
      /tmp/pip-build-env-ih3s6f7d/overlay/local/lib/python3.10/dist-packages/setuptools/config/_apply_pyprojecttoml.py:79: SetuptoolsWarning: `install_requires` overwritten in `pyproject.toml` (dependencies)
        corresp(dist, value, root_dir)
      Traceback (most recent call last):
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
        File "/tmp/pip-build-env-ih3s6f7d/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 458, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "/tmp/pip-build-env-ih3s6f7d/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/tmp/pip-build-env-ih3s6f7d/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-ih3s6f7d/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 3, in <module>
        File "/tmp/pip-build-env-ih3s6f7d/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/core.py", line 158, in setup
          dist.parse_config_files()
        File "/tmp/pip-build-env-ih3s6f7d/overlay/local/lib/python3.10/dist-packages/setuptools/dist.py", line 634, in parse_config_files
          pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
        File "/tmp/pip-build-env-ih3s6f7d/overlay/local/lib/python3.10/dist-packages/setuptools/config/pyprojecttoml.py", line 71, in apply_configuration
          return _apply(dist, config, filepath)
        File "/tmp/pip-build-env-ih3s6f7d/overlay/local/lib/python3.10/dist-packages/setuptools/config/_apply_pyprojecttoml.py", line 53, in apply
          _apply_project_table(dist, config, root_dir)
        File "/tmp/pip-build-env-ih3s6f7d/overlay/local/lib/python3.10/dist-packages/setuptools/config/_apply_pyprojecttoml.py", line 79, in _apply_project_table
          corresp(dist, value, root_dir)
        File "/tmp/pip-build-env-ih3s6f7d/overlay/local/lib/python3.10/dist-packages/setuptools/config/_apply_pyprojecttoml.py", line 181, in _license
          _set_config(dist, "license", val["text"])
      KeyError: 'text'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by abefetterman** [comment]
Thanks, the issue was an outdated setup.py file, installation should work now.
