### ISSUE TITLE
Suggestion fails because pareto groups is empty

### ISSUE THREAD

**Issue by jsuarez5341** [imbue-ai/carbs#6]
![image](https://github.com/imbue-ai/carbs/assets/14065750/e8178106-359f-417d-b8bb-7cc85d5faad2)
 
Got CARBS working on a toy env. Went to throw it on something larger and it's failing after a few trials because the pareto front is empty. Any idea what would cause this?

**Comment by abefetterman** [comment]
Did you set `num_random_samples` in your config to 0? That's the only thing that I imagine could cause it -- we recommend setting it to at least 3 (if you are running without any parallel suggestions, set it to at least the number of dimensions you have)

**Comment by jsuarez5341** [comment]
Hmm, no, but I was editing the suggestions returned by CARBS. There's a round function for linear spaces but not for exponential ones, so I was postprocessing values to make minibatches powers of 2. Will see if I repro it in the cleaned up version

**Comment by jsuarez5341** [comment]
@abefetterman Re-opening this because I found the cause of the issue, which appears to be a real bug

When num_random_samples > 1, I was getting duplicate suggestions. This then causes group_observations to produce groups where the parameters are identical, but there are multiple different costs. But the quantile computation uses the min across all observations, not across groups. So there can be no groups for which the mean is less than the quantile.

**Comment by kywch** [comment]
Hello, I got the same error, during both `suggest()` and `observe()`. 

I did a quick fix and am testing it. If my runs work well, and it looks good to you, I'll make a PR. Thank you!

https://github.com/imbue-ai/carbs/compare/main...kywch:carbs:main

**Comment by b-vm** [comment]
I've got the same bug. Been running carbs for a few months with no issues, but getting this today. @kywch I will try your pr

**Comment by b-vm** [comment]
still crashes.

```
2024-11-10 01:16:04.885 | WARNING  | carbs.utils:get_pareto_groups_conservative:573 - There is no grouped obs below min_pareto_cost. So inspect observations' cost individually.
Job on cuda:0 processed.
Job on cuda:0 starting...
Traceback (most recent call last):
  File "/home/ubuntu/train.py", line 319, in <module>
    gpu_manager.run()
  File "/home/ubuntu/train.py", line 118, in run
    config, suggestion = self.job_generator.get_next_job()
  File "/home/ubuntu/train.py", line 284, in get_next_job
    suggestion = self.carbs_runner.suggest().suggestion
  File "/home/ubuntu/carbs/carbs.py", line 177, in suggest
    suggestion_in_basic = self._get_resample_suggestion()
  File "/home/ubuntu/carbs/carbs.py", line 668, in _get_resample_suggestion
    pareto_groups = list(self._get_pareto_groups(is_conservative=False))
  File "/home/ubuntu/carbs/carbs.py", line 650, in _get_pareto_groups
    pareto_groups = get_pareto_groups(
  File "/home/ubuntu/carbs/utils.py", line 517, in get_pareto_groups
    first_pareto_group = max(
ValueError: max() arg is an empty sequence
```

**Comment by b-vm** [comment]
First time this happened, and also the first time I'm doing runs that take a lot longer, sounds similar to @jsuarez5341 ?  

If i set the number of iterations really low, it works just fine.

**Comment by kywch** [comment]
Hi @b-vm can you try https://github.com/kywch/carbs/tree/py310 this branch?

Previously, I only changed `get_pareto_groups_conservative` but your error comes from `get_pareto_groups`, due to a similar cause.  

BTW, `resample_frequency=2` gives you the previous suggestion once every two suggestions. Is that what you intended?

**Comment by b-vm** [comment]
I've since changed the experiment. If I do get the error again I will try your branch and report back.

yeah resample frequency was def wrong, thanks

**Comment by alexkstern** [comment]
Is this bug still happening for ppl?
